version: '3.5'

services:
  dashboard:
    image: charypar/swarm-dashboard:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 4040:8080
    environment:
      PORT: 8080
    deploy:
      labels:
        traefik.frontend.rule: Host:dashboard.${CLUSTER_DOMAIN}
        traefik.port: 8080
        traefik.docker.network: traefik-net
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - traefik-net

  portainer:
    image: portainer/portainer:1.17.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - 5050:9000
    volumes:
      - portainer:/data
    deploy:
      labels:
        traefik.frontend.rule: Host:portainer.${CLUSTER_DOMAIN}
        traefik.port: 9000
        traefik.docker.network: traefik-net
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - traefik-net
      - admin-net

  agent:
    image: portainer/agent:1.0.0
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - admin-net
    deploy:
      mode: global

  feeds:
    image: flaviostutz/docker-swarm-feeds:1.1.0
    ports:
      - 5353:8000
    environment:
      - FEED_NAME=${CLUSTER_DOMAIN}
    deploy:
      labels:
        traefik.frontend.rule: Host:feeds.${CLUSTER_DOMAIN}
        traefik.port: 8000
        traefik.docker.network: traefik-net
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  janitor:
    image: flaviostutz/docker-janitor:latest
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      - SLEEP_TIME=86400
      - UNUSED_TIME=24h
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  admin-net:
    driver: overlay
  traefik-net:
    external: true

volumes:
  portainer: {}
